#!/bin/zsh

# TODO: Make sure that that folder exists first
echo "Copying all the script files to ~/bin..."

cp -a ./scripts/. $HOME/bin

echo "Script files copied successfully."
cd ..

# TODO: Add to PATH